stages:
 - template: azure/stages.yml
   parameters:
     minrust: 1.34.0 # integer atomics
     codecov_token: $(CODECOV_TOKEN_SECRET)
     envs:
       ENV_IS_SET: true
     setup:
       - script: touch src/setup.rs
 # should work without code coverage token
 - template: azure/stages.yml
   parameters:
     minrust: 1.34.0 # integer atomics
     prefix: "nosecret_"
     codecov_token: $(DOES_NOT_EXIST)
     envs:
       ENV_IS_SET: true
     setup:
       - script: touch src/setup.rs
 # also test with various other configuration changes
 - template: azure/stages.yml
   parameters:
     minrust: 1.34.0 # integer atomics
     benches: true
     test_ignored: true
     prefix: "opts_"
     envs:
       ENV_IS_SET: true
     setup:
       - script: touch src/setup.rs
 # test binary-focused stages (no min rust version test)
 - template: azure/stages.yml
   parameters:
     minrust: false
     prefix: "bin_"
     envs:
       ENV_IS_SET: true
     setup:
       - script: touch src/setup.rs

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: crate-ci
